#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

void read_os_info() {
    int fd;
    char buffer[1024];
    ssize_t bytes_read;

    fd = open("/etc/os-release", O_RDONLY);
    if (fd == -1) {
        perror("Error opening /etc/os-release");
        return;
    }

    while ((bytes_read = read(fd, buffer, sizeof(buffer))) > 0) {
        write(STDOUT_FILENO, buffer, bytes_read);
    }

    close(fd);
}

void read_system_info() {
    int fd;
    char buffer[1024];
    ssize_t bytes_read;

    fd = open("/proc/version", O_RDONLY);
    if (fd == -1) {
        perror("Error opening /proc/version");
        return;
    }

    while ((bytes_read = read(fd, buffer, sizeof(buffer))) > 0) {
        write(STDOUT_FILENO, buffer, bytes_read);
    }

    close(fd);
}

void read_cpu_info() {
    int fd;
    char buffer[1024];
    ssize_t bytes_read;

    fd = open("/proc/cpuinfo", O_RDONLY);
    if (fd == -1) {
        perror("Error opening /proc/cpuinfo");
        return;
    }

    while ((bytes_read = read(fd, buffer, sizeof(buffer))) > 0) {
        write(STDOUT_FILENO, buffer, bytes_read);
    }

    close(fd);
}

int main() {
    printf("\n**Disclaimer: This application was generated by GenAI.**\n\n");

    printf("Operating System Information:\n");
    read_os_info();

    printf("\nSystem Information:\n");
    read_system_info();

    return 0;
}
