@startuml

actor user as "User"
file script as "Shell Script"

node OS {    
    agent shell as "Shell/Command Line Interpreter (CLI)"
    collections apps as "Executables"
}


user -[dashed]-> shell: [interactive] input command
script -[dashed]-> shell
shell -[dashed]down-> apps: Invoke

@enduml
